import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const leaderboardEntries = sqliteTable("leaderboard_entries", {
  playerId: text("player_id").primaryKey(),
  nickname: text("nickname").notNull(),
  totalGoals: real("total_goals").notNull().default(0),
  seasonGoals: real("season_goals").notNull().default(0),
  minigameWins: integer("minigame_wins").notNull().default(0),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const coopRooms = sqliteTable("coop_rooms", {
  code: text("code").primaryKey(),
  roomName: text("room_name").notNull().default("Meine Welt"),
  hostPlayerId: text("host_player_id").notNull(),
  hostName: text("host_name").notNull(),
  hostLastSeenAt: text("host_last_seen_at").notNull().default(""),
  guestPlayerId: text("guest_player_id"),
  guestName: text("guest_name"),
  guestLastSeenAt: text("guest_last_seen_at").notNull().default(""),
  player3PlayerId: text("player3_player_id"),
  player3Name: text("player3_name"),
  player3LastSeenAt: text("player3_last_seen_at").notNull().default(""),
  player4PlayerId: text("player4_player_id"),
  player4Name: text("player4_name"),
  player4LastSeenAt: text("player4_last_seen_at").notNull().default(""),
  sharedCoins: real("shared_coins").notNull().default(0),
  hostGoals: real("host_goals").notNull().default(0),
  guestGoals: real("guest_goals").notNull().default(0),
  player3Goals: real("player3_goals").notNull().default(0),
  player4Goals: real("player4_goals").notNull().default(0),
  hostClicks: integer("host_clicks").notNull().default(0),
  guestClicks: integer("guest_clicks").notNull().default(0),
  player3Clicks: integer("player3_clicks").notNull().default(0),
  player4Clicks: integer("player4_clicks").notNull().default(0),
  sharedUpgradeLevel: integer("shared_upgrade_level").notNull().default(0),
  sharedTotalGoals: real("shared_total_goals").notNull().default(0),
  sharedSeasonGoals: real("shared_season_goals").notNull().default(0),
  sharedUpgradesJson: text("shared_upgrades_json").notNull().default("{}"),
  sharedAchievementsJson: text("shared_achievements_json").notNull().default("[]"),
  sharedStars: integer("shared_stars").notNull().default(0),
  sharedSeasons: integer("shared_seasons").notNull().default(0),
  sharedMinigameWins: integer("shared_minigame_wins").notNull().default(0),
  sharedMiniGameCooldownsJson: text("shared_minigame_cooldowns_json").notNull().default("{}"),
  sharedFeaturesJson: text("shared_features_json").notNull().default("{}"),
  sharedStateBackupJson: text("shared_state_backup_json").notNull().default("{}"),
  sharedStateVersion: integer("shared_state_version").notNull().default(0),
  redeemedBonusCodesJson: text("redeemed_bonus_codes_json").notNull().default("[]"),
  lastPassiveAt: text("last_passive_at").notNull().default(""),
  pendingPlayerId: text("pending_player_id"),
  pendingUpgradeId: text("pending_upgrade_id"),
  pendingUpgradeName: text("pending_upgrade_name"),
  pendingCost: real("pending_cost"),
  pendingUpgradeCount: integer("pending_upgrade_count"),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
